version: "3.1"

networks:
  public-network:

  private-network:
    internal: true

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
     - "27017:27017"
    networks:
    - public-network
    - private-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: simple-chat-db
    volumes:
      - ./mongo-init.js/:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #  - ./database:/data/db # for making data available out of container

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    networks:
    - public-network
    - private-network
    depends_on:
    - mongodb
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
